// web-old/src/shared/components/SharedNavbar.jsx
/**
 * SharedNavbar.jsx — React 版统一导航栏
 * 功能与 SharedNavbar.vue 完全一致
 *
 * 使用方式：
 *   <SharedNavbar
 *     appName="认证中心"
 *     appLinks={[{ label: '设置', href: '/settings' }]}
 *     isAuthenticated={!!token}
 *     authToken={token}
 *     onLogin={handleLogin}
 *     onLogout={handleLogout}
 *   />
 */
/* eslint-disable */

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as authService from '../auth/auth-service.js';
import {
  getPortalNavCompact,
  getPortalNavLinks,
  getUnifiedProductEntries,
  getUnifiedProductEntryGroups,
  resolvePortalLoginUrl,
  resolveProductLaunchUrl,
  resolveServiceUrl,
} from '../navigation/unified-links.js';
import './SharedNavbar.css';

const MAX_TOTAL_LINKS = 8;
const PRODUCT_MENU_CLOSE_DELAY_MS = 220;

export default function SharedNavbar({
  appName,
  appLinks = [],
  isAuthenticated = false,
  authToken = null,
  hidePortalNav = false,
  onLogin,
  onLogout,
}) {
  const [theme, setTheme] = useState(() => authService.getPreferredTheme());
  const [productMenuOpen, setProductMenuOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [recentProducts, setRecentProducts] = useState([]);
  const [navConfig, setNavConfig] = useState(() => authService.getCustomNavConfig());
  const dropdownRef = useRef(null);
  const closeTimerRef = useRef(null);

  // Derived
  const hasLoginListener = typeof onLogin === 'function';

  const portalLinks = useMemo(() => {
    if (hidePortalNav) return [];
    const totalLinks = appLinks.length + (isAuthenticated ? 4 : 1);
    return totalLinks > MAX_TOTAL_LINKS ? getPortalNavCompact() : getPortalNavLinks();
  }, [hidePortalNav, appLinks.length, isAuthenticated]);

  const productEntries = useMemo(() => getUnifiedProductEntries(), []);
  const groupedProductEntries = useMemo(() => getUnifiedProductEntryGroups(), []);

  const recentVisibleProducts = useMemo(() => {
    return recentProducts
      .map((recent) => ({
        recent,
        product: productEntries.find((entry) => entry.id === recent.key),
      }))
      .filter((item) => Boolean(item.product));
  }, [recentProducts, productEntries]);

  const themeLabel = theme === 'dark' ? '切换到浅色' : '切换到暗色';

  // Helpers
  const normalizePath = (value) => value.replace(/\/+$/, '') || '/';

  const isNavLinkActive = useCallback(
    (href) => {
      try {
        const current = new URL(window.location.href);
        const target = new URL(href, window.location.origin);
        if (current.origin !== target.origin) return false;
        if (normalizePath(current.pathname) !== normalizePath(target.pathname)) return false;
        if (target.hash) return current.hash === target.hash;
        if (target.search) return current.search === target.search;
        return true;
      } catch {
        return false;
      }
    },
    [],
  );

  const getProductHref = useCallback(
    (product) => {
      return (
        resolveProductLaunchUrl(product.id || '', product.href, undefined, authToken) || product.href
      );
    },
    [authToken],
  );

  // Handlers
  const handleThemeToggle = () => {
    setTheme(authService.togglePreferredTheme());
  };

  const handleLoginClick = () => {
    if (hasLoginListener) {
      onLogin();
    } else {
      window.location.href = resolvePortalLoginUrl();
    }
  };

  const toggleMobileMenu = () => setMobileMenuOpen((v) => !v);

  const clearCloseTimer = () => {
    if (closeTimerRef.current) {
      clearTimeout(closeTimerRef.current);
      closeTimerRef.current = null;
    }
  };

  const openProductMenu = () => {
    clearCloseTimer();
    setProductMenuOpen(true);
  };

  const toggleProductMenu = () => {
    clearCloseTimer();
    setProductMenuOpen((v) => !v);
  };

  const scheduleProductMenuClose = () => {
    clearCloseTimer();
    closeTimerRef.current = setTimeout(() => {
      setProductMenuOpen(false);
      closeTimerRef.current = null;
    }, PRODUCT_MENU_CLOSE_DELAY_MS);
  };

  const handleProductClick = (product) => {
    if (product.id) {
      authService.recordProductAccess(product.id, product.label);
    }
    clearCloseTimer();
    setProductMenuOpen(false);
  };

  // Effects
  useEffect(() => {
    const stopThemeSync = authService.setupThemeSync((nextTheme) => {
      setTheme(nextTheme);
    });

    if (isAuthenticated) {
      setRecentProducts(authService.getRecentProducts());
      setNavConfig(authService.getCustomNavConfig());
    }

    const stopAuthEvent = authService.onAuthEvent((event) => {
      if (event.type === 'recent_products_updated') {
        setRecentProducts(Array.isArray(event.data) ? event.data : []);
      }
      if (event.type === 'custom_nav_updated') {
        setNavConfig(authService.getCustomNavConfig());
      }
    });

    const handleOutsideClick = (e) => {
      if (!dropdownRef.current?.contains(e.target)) {
        clearCloseTimer();
        setProductMenuOpen(false);
      }
    };

    const handleEscape = (e) => {
      if (e.key === 'Escape') {
        clearCloseTimer();
        setProductMenuOpen(false);
        setMobileMenuOpen(false);
      }
    };

    document.addEventListener('mousedown', handleOutsideClick);
    document.addEventListener('keydown', handleEscape);

    return () => {
      stopThemeSync();
      stopAuthEvent();
      clearCloseTimer();
      document.removeEventListener('mousedown', handleOutsideClick);
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isAuthenticated]);

  return (
    <header className="kx-shared-navbar">
      <nav className="kx-shared-navbar__container">
        {/* Logo */}
        <a className="kx-shared-navbar__logo" href={resolveServiceUrl('portal')}>
          <img src="/kxmemory-icon.svg" alt="开轩启圭" className="kx-shared-navbar__logo-icon" />
          <div className="kx-shared-navbar__logo-text">
            <strong>开轩启圭{appName ? ` · ${appName}` : ' 数字智能'}</strong>
          </div>
        </a>

        {/* Mobile toggle */}
        <button
          type="button"
          className="kx-shared-navbar__mobile-toggle"
          aria-expanded={mobileMenuOpen}
          aria-label="切换导航菜单"
          onClick={toggleMobileMenu}
        >
          {mobileMenuOpen ? '✕' : '☰'}
        </button>

        {/* Links */}
        <div
          className={[
            'kx-shared-navbar__links',
            mobileMenuOpen && 'kx-shared-navbar__links--mobile-open',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          {/* App links */}
          {appLinks.map((link) => (
            <a
              key={link.href}
              href={link.href}
              className={[
                'kx-shared-navbar__link',
                link.highlight && 'kx-shared-navbar__link--highlight',
                isNavLinkActive(link.href) && 'kx-shared-navbar__link--active',
              ]
                .filter(Boolean)
                .join(' ')}
              aria-current={isNavLinkActive(link.href) ? 'page' : undefined}
              target={link.external ? '_blank' : undefined}
              rel={link.external ? 'noopener noreferrer' : undefined}
            >
              {link.label}
            </a>
          ))}

          {appLinks.length > 0 && portalLinks.length > 0 && (
            <span className="kx-shared-navbar__divider" aria-hidden="true" />
          )}

          {/* Portal links */}
          {portalLinks.map((link) => (
            <a
              key={link.href}
              href={link.href}
              className={[
                'kx-shared-navbar__link',
                'kx-shared-navbar__link--portal',
                isNavLinkActive(link.href) && 'kx-shared-navbar__link--active',
              ]
                .filter(Boolean)
                .join(' ')}
              aria-current={isNavLinkActive(link.href) ? 'page' : undefined}
            >
              {link.label}
            </a>
          ))}

          {/* Product dropdown */}
          <div
            ref={dropdownRef}
            className="kx-shared-navbar__dropdown"
            onMouseEnter={openProductMenu}
            onMouseLeave={scheduleProductMenuClose}
            onFocus={openProductMenu}
          >
            <button
              type="button"
              className="kx-shared-navbar__btn-link kx-shared-navbar__btn-link--dropdown"
              aria-haspopup="true"
              aria-expanded={productMenuOpen}
              aria-label="打开产品导航"
              onClick={toggleProductMenu}
            >
              <span className="kx-shared-navbar__dropdown-trigger-label">产品</span>
              <span
                className={[
                  'kx-shared-navbar__dropdown-arrow',
                  productMenuOpen && 'is-open',
                ]
                  .filter(Boolean)
                  .join(' ')}
              >
                ▼
              </span>
            </button>

            <div
              className={[
                'kx-shared-navbar__dropdown-menu',
                productMenuOpen && 'kx-shared-navbar__dropdown-menu--open',
              ]
                .filter(Boolean)
                .join(' ')}
            >
              {/* Recent products */}
              {isAuthenticated &&
                navConfig.showRecent &&
                recentVisibleProducts.length > 0 && (
                  <>
                    <div className="kx-shared-navbar__dropdown-section">
                      <div className="kx-shared-navbar__dropdown-section-title">最近使用</div>
                    </div>
                    {recentVisibleProducts.map((item) => (
                      <a
                        key={`recent-${item.recent.key}`}
                        href={getProductHref(item.product)}
                        className="kx-shared-navbar__dropdown-item kx-shared-navbar__dropdown-item--recent"
                        target={item.product.external ? '_blank' : undefined}
                        rel={item.product.external ? 'noopener noreferrer' : undefined}
                        onClick={() => handleProductClick(item.product)}
                      >
                        <span className="kx-shared-navbar__dropdown-item-icon" aria-hidden="true">
                          {item.product.icon}
                        </span>
                        <span className="kx-shared-navbar__dropdown-item-label">
                          {item.product.label}
                        </span>
                      </a>
                    ))}
                    <div className="kx-shared-navbar__dropdown-divider" />
                  </>
                )}

              {/* Grouped products */}
              {groupedProductEntries.map((group) => (
                <React.Fragment key={group.groupLabel || 'default'}>
                  {group.groupLabel && (
                    <div className="kx-shared-navbar__dropdown-section">
                      <div className="kx-shared-navbar__dropdown-section-title">
                        {group.groupLabel}
                      </div>
                    </div>
                  )}
                  {group.items.map((product) => (
                    <a
                      key={product.id}
                      href={getProductHref(product)}
                      className="kx-shared-navbar__dropdown-item"
                      target={product.external ? '_blank' : undefined}
                      rel={product.external ? 'noopener noreferrer' : undefined}
                      onClick={() => handleProductClick(product)}
                    >
                      <span className="kx-shared-navbar__dropdown-item-icon" aria-hidden="true">
                        {product.icon}
                      </span>
                      <span className="kx-shared-navbar__dropdown-item-label">{product.label}</span>
                    </a>
                  ))}
                </React.Fragment>
              ))}
            </div>
          </div>

          {/* Theme toggle */}
          <button
            type="button"
            className="kx-shared-navbar__btn-link kx-shared-navbar__theme-toggle"
            aria-label={themeLabel}
            title={themeLabel}
            onClick={handleThemeToggle}
          >
            <span className="kx-shared-navbar__theme-toggle-label">
              {theme === 'dark' ? '浅色' : '暗色'}
            </span>
          </button>

          {/* Auth */}
          {isAuthenticated ? (
            <button
              type="button"
              className="kx-shared-navbar__btn-link kx-shared-navbar__btn-link--danger"
              onClick={onLogout}
            >
              退出
            </button>
          ) : (
            <button
              type="button"
              className="kx-shared-navbar__link kx-shared-navbar__link--highlight kx-shared-navbar__login-btn"
              onClick={handleLoginClick}
            >
              登录
            </button>
          )}
        </div>
      </nav>
    </header>
  );
}

// web-vue/src/shared/components/SharedNavbar.vue
<script setup lang="ts">
import { computed, getCurrentInstance, onBeforeUnmount, onMounted, ref } from 'vue';
import * as authService from '@/shared/auth/auth-service.js';
import {
  getPortalNavCompact,
  getPortalNavLinks,
  getUnifiedProductEntries,
  getUnifiedProductEntryGroups,
  resolvePortalLoginUrl,
  resolveProductLaunchUrl,
  resolveServiceUrl,
} from '@/shared/navigation/unified-links';
import './SharedNavbar.css';

type NavLink = {
  id?: string;
  label: string;
  href: string;
  external?: boolean;
  highlight?: boolean;
  icon?: string;
};

const props = withDefaults(
  defineProps<{
    appName?: string;
    appLinks?: NavLink[];
    isAuthenticated?: boolean;
    authToken?: string | null;
    hidePortalNav?: boolean;
  }>(),
  {
    appName: undefined,
    appLinks: () => [],
    isAuthenticated: false,
    authToken: null,
    hidePortalNav: false,
  },
);

const emit = defineEmits<{
  login: [];
  logout: [];
}>();

const hasLoginListener = computed(() => {
  const instance = getCurrentInstance();
  return Boolean(instance?.vnode.props?.onLogin);
});

const MAX_TOTAL_LINKS = 8;
const PRODUCT_MENU_CLOSE_DELAY_MS = 220;
const dropdownRef = ref<HTMLElement | null>(null);
const isProductMenuOpen = ref(false);
const isMobileMenuOpen = ref(false);
const theme = ref<'daylight' | 'night'>(authService.getPreferredTheme());
const recentProducts = ref<{ key: string; name: string; timestamp: number }[]>([]);
const navConfig = ref(authService.getCustomNavConfig());
let closeMenuTimer: ReturnType<typeof setTimeout> | null = null;

const portalLinks = computed(() => {
  if (props.hidePortalNav) {
    return [];
  }
  const totalLinks = props.appLinks.length + (props.isAuthenticated ? 4 : 1);
  return totalLinks > MAX_TOTAL_LINKS ? getPortalNavCompact() : getPortalNavLinks();
});

const productEntries = computed(() => getUnifiedProductEntries());
const groupedProductEntries = computed(() => getUnifiedProductEntryGroups());

const recentVisibleProducts = computed(() => {
  return recentProducts.value
    .map((recent) => ({
      recent,
      product: productEntries.value.find((entry) => entry.id === recent.key),
    }))
    .filter(
      (item): item is { recent: { key: string; name: string; timestamp: number }; product: NavLink } =>
        Boolean(item.product),
    );
});

const themeLabel = computed(() => (theme.value === 'night' ? '切换到白昼' : '切换到暗夜'));

function normalizePath(value: string) {
  const normalized = value.replace(/\/+$/, '');
  return normalized || '/';
}

function isNavLinkActive(href: string) {
  if (typeof window === 'undefined') return false;
  try {
    const current = new URL(window.location.href);
    const target = new URL(href, window.location.origin);
    if (current.origin !== target.origin) return false;
    if (normalizePath(current.pathname) !== normalizePath(target.pathname)) return false;
    if (target.hash) return current.hash === target.hash;
    if (target.search) return current.search === target.search;
    return true;
  } catch {
    return false;
  }
}

function getProductHref(product: NavLink) {
  return resolveProductLaunchUrl(product.id || '', product.href, undefined, props.authToken) || product.href;
}

function handleThemeToggle() {
  theme.value = authService.togglePreferredTheme();
}

function handleLoginClick() {
  if (hasLoginListener.value) {
    emit('login');
  } else {
    window.location.href = resolvePortalLoginUrl();
  }
}

function toggleMobileMenu() {
  isMobileMenuOpen.value = !isMobileMenuOpen.value;
}

function clearCloseMenuTimer() {
  if (closeMenuTimer !== null) {
    clearTimeout(closeMenuTimer);
    closeMenuTimer = null;
  }
}

function openProductMenu() {
  clearCloseMenuTimer();
  isProductMenuOpen.value = true;
}

function toggleProductMenu() {
  clearCloseMenuTimer();
  isProductMenuOpen.value = !isProductMenuOpen.value;
}

function scheduleProductMenuClose() {
  clearCloseMenuTimer();
  closeMenuTimer = setTimeout(() => {
    isProductMenuOpen.value = false;
    closeMenuTimer = null;
  }, PRODUCT_MENU_CLOSE_DELAY_MS);
}

function handleOutsideClick(event: MouseEvent) {
  if (!dropdownRef.value?.contains(event.target as Node)) {
    clearCloseMenuTimer();
    isProductMenuOpen.value = false;
  }
}

function handleEscape(event: KeyboardEvent) {
  if (event.key === 'Escape') {
    clearCloseMenuTimer();
    isProductMenuOpen.value = false;
    isMobileMenuOpen.value = false;
  }
}

function handleProductClick(product: NavLink) {
  if (product.id) {
    authService.recordProductAccess(product.id, product.label);
  }
  clearCloseMenuTimer();
  isProductMenuOpen.value = false;
}

let stopThemeSync: (() => void) | null = null;
let stopAuthEvent: (() => void) | null = null;

onMounted(() => {
  stopThemeSync = authService.setupThemeSync((nextTheme) => {
    theme.value = nextTheme;
  });

  if (props.isAuthenticated) {
    recentProducts.value = authService.getRecentProducts();
    navConfig.value = authService.getCustomNavConfig();
  }

  stopAuthEvent = authService.onAuthEvent((event: { type: string; data?: unknown }) => {
    if (event.type === 'recent_products_updated') {
      recentProducts.value = Array.isArray(event.data)
        ? (event.data as { key: string; name: string; timestamp: number }[])
        : [];
    }
    if (event.type === 'custom_nav_updated') {
      navConfig.value = authService.getCustomNavConfig();
    }
  });

  document.addEventListener('mousedown', handleOutsideClick);
  document.addEventListener('keydown', handleEscape);
});

onBeforeUnmount(() => {
  stopThemeSync?.();
  stopAuthEvent?.();
  clearCloseMenuTimer();
  document.removeEventListener('mousedown', handleOutsideClick);
  document.removeEventListener('keydown', handleEscape);
});
</script>

<template>
  <header class="kx-shared-navbar">
    <nav class="kx-shared-navbar__container">
      <a class="kx-shared-navbar__logo" :href="resolveServiceUrl('portal')">
        <img src="/assets/logo-icon.svg" alt="开轩启圭" class="kx-shared-navbar__logo-icon" />
        <div class="kx-shared-navbar__logo-text">
          <span class="kx-brand-main">开轩启圭</span>
          <span v-if="appName" class="kx-brand-separator">·</span>
          <span v-if="appName" class="kx-brand-product">{{ appName }}</span>
          <span v-else class="kx-brand-product">数字智能</span>
        </div>
      </a>

      <button
        type="button"
        class="kx-shared-navbar__mobile-toggle"
        :aria-expanded="isMobileMenuOpen"
        aria-label="切换导航菜单"
        @click="toggleMobileMenu"
      >
        {{ isMobileMenuOpen ? '✕' : '☰' }}
      </button>

      <div :class="['kx-shared-navbar__links', isMobileMenuOpen && 'kx-shared-navbar__links--mobile-open', $slots['workspace-nav'] && 'kx-shared-navbar__links--workspace-mode']">
        <a
          v-for="link in appLinks"
          :key="link.href"
          :href="link.href"
          :class="[
            'kx-shared-navbar__link',
            link.highlight && 'kx-shared-navbar__link--highlight',
            isNavLinkActive(link.href) && 'kx-shared-navbar__link--active',
          ]"
          :aria-current="isNavLinkActive(link.href) ? 'page' : undefined"
          :target="link.external ? '_blank' : undefined"
          :rel="link.external ? 'noopener noreferrer' : undefined"
        >
          {{ link.label }}
        </a>

        <slot name="workspace-nav" />
        <div v-if="$slots['workspace-nav']" class="kx-shared-navbar__workspace-spacer" aria-hidden="true" />

        <span
          v-if="(appLinks.length > 0 || !!$slots['workspace-nav']) && portalLinks.length > 0"
          class="kx-shared-navbar__divider"
          aria-hidden="true"
        />

        <a
          v-for="link in portalLinks"
          :key="link.href"
          :href="link.href"
          :class="[
            'kx-shared-navbar__link',
            'kx-shared-navbar__link--portal',
            isNavLinkActive(link.href) && 'kx-shared-navbar__link--active',
          ]"
          :aria-current="isNavLinkActive(link.href) ? 'page' : undefined"
        >
          {{ link.label }}
        </a>

        <div
          ref="dropdownRef"
          class="kx-shared-navbar__dropdown"
          @mouseenter="openProductMenu"
          @mouseleave="scheduleProductMenuClose"
          @focusin="openProductMenu"
        >
          <button
            type="button"
            class="kx-shared-navbar__btn-link kx-shared-navbar__btn-link--dropdown"
            aria-haspopup="true"
            :aria-expanded="isProductMenuOpen"
            aria-label="打开产品导航"
            @click="toggleProductMenu"
          >
            <span class="kx-shared-navbar__dropdown-trigger-label">产品</span>
            <span :class="['kx-shared-navbar__dropdown-arrow', isProductMenuOpen && 'is-open']">▼</span>
          </button>

          <div :class="['kx-shared-navbar__dropdown-menu', isProductMenuOpen && 'kx-shared-navbar__dropdown-menu--open']">
            <template v-if="isAuthenticated && navConfig.showRecent && recentVisibleProducts.length > 0">
              <div class="kx-shared-navbar__dropdown-section">
                <div class="kx-shared-navbar__dropdown-section-title">最近使用</div>
              </div>

              <a
                v-for="item in recentVisibleProducts"
                :key="`recent-${item.recent.key}`"
                :href="getProductHref(item.product)"
                class="kx-shared-navbar__dropdown-item kx-shared-navbar__dropdown-item--recent"
                :target="item.product.external ? '_blank' : undefined"
                :rel="item.product.external ? 'noopener noreferrer' : undefined"
                @click="handleProductClick(item.product)"
              >
                <span class="kx-shared-navbar__dropdown-item-icon" aria-hidden="true">{{ item.product.icon }}</span>
                <span class="kx-shared-navbar__dropdown-item-label">{{ item.product.label }}</span>
              </a>

              <div class="kx-shared-navbar__dropdown-divider" />
            </template>

            <div v-for="group in groupedProductEntries" :key="group.groupLabel || 'default'">
              <div v-if="group.groupLabel" class="kx-shared-navbar__dropdown-section">
                <div class="kx-shared-navbar__dropdown-section-title">{{ group.groupLabel }}</div>
              </div>

              <a
                v-for="product in group.items"
                :key="product.id"
                :href="getProductHref(product)"
                class="kx-shared-navbar__dropdown-item"
                :target="product.external ? '_blank' : undefined"
                :rel="product.external ? 'noopener noreferrer' : undefined"
                @click="handleProductClick(product)"
              >
                <span class="kx-shared-navbar__dropdown-item-icon" aria-hidden="true">{{ product.icon }}</span>
                <span class="kx-shared-navbar__dropdown-item-label">{{ product.label }}</span>
              </a>
            </div>
          </div>
        </div>

        <button
          v-if="!$slots['status-actions']"
          type="button"
          class="kx-shared-navbar__btn-link kx-shared-navbar__theme-toggle"
          :aria-label="themeLabel"
          :title="themeLabel"
          @click="handleThemeToggle"
        >
          <span class="kx-shared-navbar__theme-toggle-label">{{ theme === 'night' ? '白昼' : '暗夜' }}</span>
        </button>

        <slot name="status-actions" />

        <button
          v-if="isAuthenticated"
          type="button"
          class="kx-shared-navbar__btn-link kx-shared-navbar__btn-link--danger"
          @click="emit('logout')"
        >
          退出
        </button>
        <button
          v-else
          type="button"
          class="kx-shared-navbar__link kx-shared-navbar__link--highlight kx-shared-navbar__login-btn"
          @click="handleLoginClick"
        >
          登录
        </button>
      </div>
    </nav>
  </header>
</template>
